spring:
# Database configuration
  datasource:
    url: jdbc:h2:mem:task
    username: sa
    password:
    driver-class-name: org.h2.Driver
# JPA configuration
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        default_schema: public
        multi_tenancy: DISCRIMINATOR
        tenant_identifier_resolver: com.felfel.dealer_vehicle_inventory_module.tenant.TenantIdentifierResolver
        discriminator_column_name: tenant_id
        discriminator_column_type: STRING
        tenant_identifier_binding_mode: IMPLICIT
        globally.quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true

# H2 Console configuration
  h2:
    console:
    enabled: true
    path: /h2-console
# Logging configuration
  logging:
    level:
      org: springframework=INFO
      com: example=DEBUG
